script: find ./*_test.sh | xargs -I file bash file
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5fa48284b083e11ae5e1
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
